//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/Inputs/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""perso"",
            ""id"": ""0b618132-4be4-4b59-a576-51538f00d6ab"",
            ""actions"": [
                {
                    ""name"": ""dodge"",
                    ""type"": ""Button"",
                    ""id"": ""626e002f-1d0c-46ed-a93a-c31a8ff7ea63"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""interact"",
                    ""type"": ""Button"",
                    ""id"": ""430686be-26cd-40e4-9321-059ac16b6dbd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""attack"",
                    ""type"": ""Button"",
                    ""id"": ""a71c9118-1699-4f9c-96b6-f90a0e6134e5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""run"",
                    ""type"": ""Value"",
                    ""id"": ""0948f1ba-942c-47be-b02f-249a908482fc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""useConso"",
                    ""type"": ""Button"",
                    ""id"": ""af9057fb-3fd3-4bb3-bb36-27d0f1b16911"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""randomTalk"",
                    ""type"": ""Button"",
                    ""id"": ""9ba0cfaf-4138-4dc5-9ba2-7ec2dbfdd46f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""015437b9-5c3f-4197-b941-6c30eb1c63de"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""93b1a724-d3ff-4856-88c9-ac6ce6414518"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db59ca6f-ab5b-4fbc-a6f9-60c0feb7cddd"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e26258b-b4ea-4ef6-a1eb-9a22f3f02dcf"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""493cb05f-36e7-4cc6-bca3-c7aa1148e65c"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75dfc87d-e548-4042-8a15-def507bbd239"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""useConso"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9302c95f-072e-4189-9646-1b7b70d17571"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""useConso"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c733c319-9b13-4a35-970c-ef0700b874a0"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f045da71-1f36-4421-b579-e1f39b4e2fc8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c3a8f46-555c-4048-9390-4eff923ebcc7"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""randomTalk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caed2b77-a8cc-4ff6-a9c9-259965ac1618"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""randomTalk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""main"",
                    ""id"": ""a790b397-bc9b-45c6-8820-f7ca3beeb354"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7b5817fb-83bc-4651-a14d-eef1e59d19c6"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0b628490-0749-4f26-809f-a5088fbb3879"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d06d7950-86de-4867-b9aa-efc887de713e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1b29433d-fd9b-4d35-bd37-ee52d4241784"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""abd4c902-ac54-422d-b5de-f99f2f8336e7"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a880233-268d-4325-a8e7-c04a8a371d18"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ffde1d2d-6a8f-4c9e-95d8-73f82c723019"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""eabb19b5-c974-4c9a-ba69-71b4bad173e5"",
            ""actions"": [
                {
                    ""name"": ""navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6081c15c-8c3f-4213-beb2-816695cc650c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""scroll"",
                    ""type"": ""PassThrough"",
                    ""id"": ""15949233-a652-4133-92ec-24cbee81ac13"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""activate"",
                    ""type"": ""Button"",
                    ""id"": ""bfb0aa0c-6049-4ece-a264-cceaa2a55caa"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""y"",
                    ""type"": ""Button"",
                    ""id"": ""d54f75d2-9814-4e30-b26b-b3e8fdee853f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""x"",
                    ""type"": ""Button"",
                    ""id"": ""9cabf8d8-163a-4ae7-a331-3f1b721b0fa6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""cancel"",
                    ""type"": ""Button"",
                    ""id"": ""ab61f265-6045-46c4-8b6b-c5a9ed876406"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""map"",
                    ""type"": ""Button"",
                    ""id"": ""7b064787-d4ee-411b-9d58-cc8de14ac49c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""pause"",
                    ""type"": ""Button"",
                    ""id"": ""8c3be1a7-a134-4c4a-b3a4-23c1fd093e13"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""inventory"",
                    ""type"": ""Button"",
                    ""id"": ""718497a6-ea54-4f17-b02c-205863a9f65e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3572067e-9738-49b0-b697-7f44a8028c52"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bbfd291-7f88-4772-9484-02def75ea68a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""activate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f98d722-89bc-4fb1-aa77-d39c92400099"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""activate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db8fd403-f280-4b0d-bd26-04895a2fe4bf"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6cad4bee-91f4-4954-a619-bc892eb9dd41"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38c48ac6-6251-4242-ae36-ea4569e66299"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""x"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8189062-e74c-453b-9a85-95be6e098fa2"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""x"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be124d9a-1060-4a7f-8d76-0557f62268da"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49f35044-050b-4cc3-b916-8423213986ba"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";keyboard"",
                    ""action"": ""cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5db0f43c-0654-403f-b602-382b2dd62f9b"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0a42db0-1e1b-4c9c-91d3-2275302c18f0"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1dbacae-8c74-40d7-8d4f-089e3bc5ca8c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49a8428e-3087-4a83-849e-59e20891b6e7"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f55fd782-031b-4d1f-987c-9bc79c5a6ec8"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a470b7e-21b0-45b1-82d4-c46d97adb659"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40aa7c62-2967-4cd0-8d2d-b45ec65ebd01"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c0a8b72-8e5e-45e1-9023-ebb901460c68"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";keyboard"",
                    ""action"": ""scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5c9c281-b6e3-44ad-a473-122f4f67ac3c"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""enhanced_perso"",
            ""id"": ""496fb706-37aa-4ede-8ba7-f8a5dfa615a7"",
            ""actions"": [
                {
                    ""name"": ""hack"",
                    ""type"": ""Button"",
                    ""id"": ""7ccb0cc6-c229-46ca-974b-ed8cb2b5d5ef"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hackDirection"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d41e8cc6-f0a5-4d64-b135-7e5433b38655"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""30be72d1-30ce-48e3-aa76-32f91b036399"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""hack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3454cd75-ad46-4aa5-9531-800fc03b3ee8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""hack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9f1a2ee-e589-4195-88f3-118d8282c227"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""hackDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21447ab3-5393-4a27-ae78-45de43cee0bc"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""hackDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""any"",
            ""id"": ""b1da777d-2f34-478e-a36e-cbf8e11ead69"",
            ""actions"": [
                {
                    ""name"": ""keyboard"",
                    ""type"": ""Button"",
                    ""id"": ""6e57fb60-629f-48f4-bdf3-7f45b10dc40c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""gamepad"",
                    ""type"": ""Button"",
                    ""id"": ""dbd36913-9d8c-4b0f-8abf-e0807a05608e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1d5b2ca5-9020-4d69-b8cc-22be0fd6a5e6"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c96d260-1a5e-4d2e-9e03-0185e5622064"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6160e4d3-f089-4f6c-9438-7abd69ccfc31"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8e4fcf1-bad4-4b5f-8e63-1ac1eeef3327"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3f9e357-7a48-44aa-95af-d357d05c2df0"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""561714bc-c23f-4a9b-8dc6-7a8a99ba80f6"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d45d388-4bd1-4565-8ad1-449cde8eab58"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdcf5022-a51c-451f-810c-75272545fb8e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c66983f9-09ea-450d-aee9-e90c857a47a2"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba978914-6a53-4ea5-8a51-5df86ba9132e"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea21c2c4-cb2c-4d5f-a7b0-3d0815197173"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""148efc5d-3697-49f9-82ae-78d16b5cb058"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aca169ff-c178-4d33-8ce5-bccc0482ee68"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""294eda9d-98e3-4c12-a59f-71789739f982"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce8d2aed-6244-4fa3-98e0-6d96ca10e94d"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1d74cc3-1089-48f1-b2ac-caa63ed16cf0"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c86cfd5f-4355-448a-844e-a889ff3be460"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab4b4545-a3d0-46dc-8531-273b5a52d23c"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1058e1c-2813-41f5-8db7-5f917e01ca5f"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bda0c4d8-aef0-433a-9aec-75814f3bd370"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09bab292-7f47-4cfe-914c-1e522dd0a368"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""633c244f-16bc-45f4-837c-9ec75aaf4099"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d91f3136-86d0-4012-825b-1e0263b46e1a"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4a53adb-d1fc-4e1f-b599-bfb95736ab5b"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fce0293-509b-4908-b938-e8d90cf4b3be"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d006b759-b75f-42b0-baaa-ef9df26daad2"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""285c888d-efa7-4ced-9ee0-8dbb6463d43f"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5e6230f-8733-4125-aa5f-7ab8129cb90b"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""365de825-265c-49d4-a60a-416612c66f10"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f50780fd-ab1c-43cb-b8fd-0c241c5b1dbd"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62c82b2e-da86-4c0d-b84f-3f38e32a7c68"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41f78594-5454-42a1-b25f-04e178aa3f4f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""beac541a-11b5-4daf-b4bc-6a472bd9de4e"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4919853-a48f-484b-a35a-b5bc234368ce"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xbox"",
                    ""action"": ""gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""xbox"",
            ""bindingGroup"": ""xbox"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""keyboard"",
            ""bindingGroup"": ""keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // perso
        m_perso = asset.FindActionMap("perso", throwIfNotFound: true);
        m_perso_dodge = m_perso.FindAction("dodge", throwIfNotFound: true);
        m_perso_interact = m_perso.FindAction("interact", throwIfNotFound: true);
        m_perso_attack = m_perso.FindAction("attack", throwIfNotFound: true);
        m_perso_run = m_perso.FindAction("run", throwIfNotFound: true);
        m_perso_useConso = m_perso.FindAction("useConso", throwIfNotFound: true);
        m_perso_randomTalk = m_perso.FindAction("randomTalk", throwIfNotFound: true);
        m_perso_move = m_perso.FindAction("move", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_navigate = m_UI.FindAction("navigate", throwIfNotFound: true);
        m_UI_scroll = m_UI.FindAction("scroll", throwIfNotFound: true);
        m_UI_activate = m_UI.FindAction("activate", throwIfNotFound: true);
        m_UI_y = m_UI.FindAction("y", throwIfNotFound: true);
        m_UI_x = m_UI.FindAction("x", throwIfNotFound: true);
        m_UI_cancel = m_UI.FindAction("cancel", throwIfNotFound: true);
        m_UI_map = m_UI.FindAction("map", throwIfNotFound: true);
        m_UI_pause = m_UI.FindAction("pause", throwIfNotFound: true);
        m_UI_inventory = m_UI.FindAction("inventory", throwIfNotFound: true);
        // enhanced_perso
        m_enhanced_perso = asset.FindActionMap("enhanced_perso", throwIfNotFound: true);
        m_enhanced_perso_hack = m_enhanced_perso.FindAction("hack", throwIfNotFound: true);
        m_enhanced_perso_hackDirection = m_enhanced_perso.FindAction("hackDirection", throwIfNotFound: true);
        // any
        m_any = asset.FindActionMap("any", throwIfNotFound: true);
        m_any_keyboard = m_any.FindAction("keyboard", throwIfNotFound: true);
        m_any_gamepad = m_any.FindAction("gamepad", throwIfNotFound: true);
    }

    ~@PlayerInputActions()
    {
        UnityEngine.Debug.Assert(!m_perso.enabled, "This will cause a leak and performance issues, PlayerInputActions.perso.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, PlayerInputActions.UI.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_enhanced_perso.enabled, "This will cause a leak and performance issues, PlayerInputActions.enhanced_perso.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_any.enabled, "This will cause a leak and performance issues, PlayerInputActions.any.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // perso
    private readonly InputActionMap m_perso;
    private List<IPersoActions> m_PersoActionsCallbackInterfaces = new List<IPersoActions>();
    private readonly InputAction m_perso_dodge;
    private readonly InputAction m_perso_interact;
    private readonly InputAction m_perso_attack;
    private readonly InputAction m_perso_run;
    private readonly InputAction m_perso_useConso;
    private readonly InputAction m_perso_randomTalk;
    private readonly InputAction m_perso_move;
    public struct PersoActions
    {
        private @PlayerInputActions m_Wrapper;
        public PersoActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @dodge => m_Wrapper.m_perso_dodge;
        public InputAction @interact => m_Wrapper.m_perso_interact;
        public InputAction @attack => m_Wrapper.m_perso_attack;
        public InputAction @run => m_Wrapper.m_perso_run;
        public InputAction @useConso => m_Wrapper.m_perso_useConso;
        public InputAction @randomTalk => m_Wrapper.m_perso_randomTalk;
        public InputAction @move => m_Wrapper.m_perso_move;
        public InputActionMap Get() { return m_Wrapper.m_perso; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PersoActions set) { return set.Get(); }
        public void AddCallbacks(IPersoActions instance)
        {
            if (instance == null || m_Wrapper.m_PersoActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PersoActionsCallbackInterfaces.Add(instance);
            @dodge.started += instance.OnDodge;
            @dodge.performed += instance.OnDodge;
            @dodge.canceled += instance.OnDodge;
            @interact.started += instance.OnInteract;
            @interact.performed += instance.OnInteract;
            @interact.canceled += instance.OnInteract;
            @attack.started += instance.OnAttack;
            @attack.performed += instance.OnAttack;
            @attack.canceled += instance.OnAttack;
            @run.started += instance.OnRun;
            @run.performed += instance.OnRun;
            @run.canceled += instance.OnRun;
            @useConso.started += instance.OnUseConso;
            @useConso.performed += instance.OnUseConso;
            @useConso.canceled += instance.OnUseConso;
            @randomTalk.started += instance.OnRandomTalk;
            @randomTalk.performed += instance.OnRandomTalk;
            @randomTalk.canceled += instance.OnRandomTalk;
            @move.started += instance.OnMove;
            @move.performed += instance.OnMove;
            @move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IPersoActions instance)
        {
            @dodge.started -= instance.OnDodge;
            @dodge.performed -= instance.OnDodge;
            @dodge.canceled -= instance.OnDodge;
            @interact.started -= instance.OnInteract;
            @interact.performed -= instance.OnInteract;
            @interact.canceled -= instance.OnInteract;
            @attack.started -= instance.OnAttack;
            @attack.performed -= instance.OnAttack;
            @attack.canceled -= instance.OnAttack;
            @run.started -= instance.OnRun;
            @run.performed -= instance.OnRun;
            @run.canceled -= instance.OnRun;
            @useConso.started -= instance.OnUseConso;
            @useConso.performed -= instance.OnUseConso;
            @useConso.canceled -= instance.OnUseConso;
            @randomTalk.started -= instance.OnRandomTalk;
            @randomTalk.performed -= instance.OnRandomTalk;
            @randomTalk.canceled -= instance.OnRandomTalk;
            @move.started -= instance.OnMove;
            @move.performed -= instance.OnMove;
            @move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IPersoActions instance)
        {
            if (m_Wrapper.m_PersoActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPersoActions instance)
        {
            foreach (var item in m_Wrapper.m_PersoActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PersoActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PersoActions @perso => new PersoActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_navigate;
    private readonly InputAction m_UI_scroll;
    private readonly InputAction m_UI_activate;
    private readonly InputAction m_UI_y;
    private readonly InputAction m_UI_x;
    private readonly InputAction m_UI_cancel;
    private readonly InputAction m_UI_map;
    private readonly InputAction m_UI_pause;
    private readonly InputAction m_UI_inventory;
    public struct UIActions
    {
        private @PlayerInputActions m_Wrapper;
        public UIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @navigate => m_Wrapper.m_UI_navigate;
        public InputAction @scroll => m_Wrapper.m_UI_scroll;
        public InputAction @activate => m_Wrapper.m_UI_activate;
        public InputAction @y => m_Wrapper.m_UI_y;
        public InputAction @x => m_Wrapper.m_UI_x;
        public InputAction @cancel => m_Wrapper.m_UI_cancel;
        public InputAction @map => m_Wrapper.m_UI_map;
        public InputAction @pause => m_Wrapper.m_UI_pause;
        public InputAction @inventory => m_Wrapper.m_UI_inventory;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @navigate.started += instance.OnNavigate;
            @navigate.performed += instance.OnNavigate;
            @navigate.canceled += instance.OnNavigate;
            @scroll.started += instance.OnScroll;
            @scroll.performed += instance.OnScroll;
            @scroll.canceled += instance.OnScroll;
            @activate.started += instance.OnActivate;
            @activate.performed += instance.OnActivate;
            @activate.canceled += instance.OnActivate;
            @y.started += instance.OnY;
            @y.performed += instance.OnY;
            @y.canceled += instance.OnY;
            @x.started += instance.OnX;
            @x.performed += instance.OnX;
            @x.canceled += instance.OnX;
            @cancel.started += instance.OnCancel;
            @cancel.performed += instance.OnCancel;
            @cancel.canceled += instance.OnCancel;
            @map.started += instance.OnMap;
            @map.performed += instance.OnMap;
            @map.canceled += instance.OnMap;
            @pause.started += instance.OnPause;
            @pause.performed += instance.OnPause;
            @pause.canceled += instance.OnPause;
            @inventory.started += instance.OnInventory;
            @inventory.performed += instance.OnInventory;
            @inventory.canceled += instance.OnInventory;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @navigate.started -= instance.OnNavigate;
            @navigate.performed -= instance.OnNavigate;
            @navigate.canceled -= instance.OnNavigate;
            @scroll.started -= instance.OnScroll;
            @scroll.performed -= instance.OnScroll;
            @scroll.canceled -= instance.OnScroll;
            @activate.started -= instance.OnActivate;
            @activate.performed -= instance.OnActivate;
            @activate.canceled -= instance.OnActivate;
            @y.started -= instance.OnY;
            @y.performed -= instance.OnY;
            @y.canceled -= instance.OnY;
            @x.started -= instance.OnX;
            @x.performed -= instance.OnX;
            @x.canceled -= instance.OnX;
            @cancel.started -= instance.OnCancel;
            @cancel.performed -= instance.OnCancel;
            @cancel.canceled -= instance.OnCancel;
            @map.started -= instance.OnMap;
            @map.performed -= instance.OnMap;
            @map.canceled -= instance.OnMap;
            @pause.started -= instance.OnPause;
            @pause.performed -= instance.OnPause;
            @pause.canceled -= instance.OnPause;
            @inventory.started -= instance.OnInventory;
            @inventory.performed -= instance.OnInventory;
            @inventory.canceled -= instance.OnInventory;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);

    // enhanced_perso
    private readonly InputActionMap m_enhanced_perso;
    private List<IEnhanced_persoActions> m_Enhanced_persoActionsCallbackInterfaces = new List<IEnhanced_persoActions>();
    private readonly InputAction m_enhanced_perso_hack;
    private readonly InputAction m_enhanced_perso_hackDirection;
    public struct Enhanced_persoActions
    {
        private @PlayerInputActions m_Wrapper;
        public Enhanced_persoActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @hack => m_Wrapper.m_enhanced_perso_hack;
        public InputAction @hackDirection => m_Wrapper.m_enhanced_perso_hackDirection;
        public InputActionMap Get() { return m_Wrapper.m_enhanced_perso; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Enhanced_persoActions set) { return set.Get(); }
        public void AddCallbacks(IEnhanced_persoActions instance)
        {
            if (instance == null || m_Wrapper.m_Enhanced_persoActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Enhanced_persoActionsCallbackInterfaces.Add(instance);
            @hack.started += instance.OnHack;
            @hack.performed += instance.OnHack;
            @hack.canceled += instance.OnHack;
            @hackDirection.started += instance.OnHackDirection;
            @hackDirection.performed += instance.OnHackDirection;
            @hackDirection.canceled += instance.OnHackDirection;
        }

        private void UnregisterCallbacks(IEnhanced_persoActions instance)
        {
            @hack.started -= instance.OnHack;
            @hack.performed -= instance.OnHack;
            @hack.canceled -= instance.OnHack;
            @hackDirection.started -= instance.OnHackDirection;
            @hackDirection.performed -= instance.OnHackDirection;
            @hackDirection.canceled -= instance.OnHackDirection;
        }

        public void RemoveCallbacks(IEnhanced_persoActions instance)
        {
            if (m_Wrapper.m_Enhanced_persoActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IEnhanced_persoActions instance)
        {
            foreach (var item in m_Wrapper.m_Enhanced_persoActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Enhanced_persoActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Enhanced_persoActions @enhanced_perso => new Enhanced_persoActions(this);

    // any
    private readonly InputActionMap m_any;
    private List<IAnyActions> m_AnyActionsCallbackInterfaces = new List<IAnyActions>();
    private readonly InputAction m_any_keyboard;
    private readonly InputAction m_any_gamepad;
    public struct AnyActions
    {
        private @PlayerInputActions m_Wrapper;
        public AnyActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @keyboard => m_Wrapper.m_any_keyboard;
        public InputAction @gamepad => m_Wrapper.m_any_gamepad;
        public InputActionMap Get() { return m_Wrapper.m_any; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AnyActions set) { return set.Get(); }
        public void AddCallbacks(IAnyActions instance)
        {
            if (instance == null || m_Wrapper.m_AnyActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AnyActionsCallbackInterfaces.Add(instance);
            @keyboard.started += instance.OnKeyboard;
            @keyboard.performed += instance.OnKeyboard;
            @keyboard.canceled += instance.OnKeyboard;
            @gamepad.started += instance.OnGamepad;
            @gamepad.performed += instance.OnGamepad;
            @gamepad.canceled += instance.OnGamepad;
        }

        private void UnregisterCallbacks(IAnyActions instance)
        {
            @keyboard.started -= instance.OnKeyboard;
            @keyboard.performed -= instance.OnKeyboard;
            @keyboard.canceled -= instance.OnKeyboard;
            @gamepad.started -= instance.OnGamepad;
            @gamepad.performed -= instance.OnGamepad;
            @gamepad.canceled -= instance.OnGamepad;
        }

        public void RemoveCallbacks(IAnyActions instance)
        {
            if (m_Wrapper.m_AnyActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAnyActions instance)
        {
            foreach (var item in m_Wrapper.m_AnyActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AnyActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AnyActions @any => new AnyActions(this);
    private int m_xboxSchemeIndex = -1;
    public InputControlScheme xboxScheme
    {
        get
        {
            if (m_xboxSchemeIndex == -1) m_xboxSchemeIndex = asset.FindControlSchemeIndex("xbox");
            return asset.controlSchemes[m_xboxSchemeIndex];
        }
    }
    private int m_keyboardSchemeIndex = -1;
    public InputControlScheme keyboardScheme
    {
        get
        {
            if (m_keyboardSchemeIndex == -1) m_keyboardSchemeIndex = asset.FindControlSchemeIndex("keyboard");
            return asset.controlSchemes[m_keyboardSchemeIndex];
        }
    }
    public interface IPersoActions
    {
        void OnDodge(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnUseConso(InputAction.CallbackContext context);
        void OnRandomTalk(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnNavigate(InputAction.CallbackContext context);
        void OnScroll(InputAction.CallbackContext context);
        void OnActivate(InputAction.CallbackContext context);
        void OnY(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnMap(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
    }
    public interface IEnhanced_persoActions
    {
        void OnHack(InputAction.CallbackContext context);
        void OnHackDirection(InputAction.CallbackContext context);
    }
    public interface IAnyActions
    {
        void OnKeyboard(InputAction.CallbackContext context);
        void OnGamepad(InputAction.CallbackContext context);
    }
}
